config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  resources :templates

  root to: "pages#home"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/template.rb
class Template < ApplicationRecord
  mount_uploader :picture, PictureUploader
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/templates_controller.rb
class TemplatesController < ApplicationController
  before_action :set_template, only: [:show, :edit, :update, :destroy]

  # GET /templates
  # GET /templates.json
  def index
    @templates = Template.all
  end

  # GET /templates/1
  # GET /templates/1.json
  def show
  end

  # GET /templates/new
  def new
    @template = Template.new
  end

  # GET /templates/1/edit
  def edit
  end

  # POST /templates
  # POST /templates.json
  def create
    @template = Template.new(template_params)

    respond_to do |format|
      if @template.save
        format.html { redirect_to @template, notice: 'Template was successfully created.' }
        format.json { render :show, status: :created, location: @template }
      else
        format.html { render :new }
        format.json { render json: @template.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /templates/1
  # PATCH/PUT /templates/1.json
  def update
    respond_to do |format|
      if @template.update(template_params)
        format.html { redirect_to @template, notice: 'Template was successfully updated.' }
        format.json { render :show, status: :ok, location: @template }
      else
        format.html { render :edit }
        format.json { render json: @template.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /templates/1
  # DELETE /templates/1.json
  def destroy
    @template.destroy
    respond_to do |format|
      format.html { redirect_to templates_url, notice: 'Template was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_template
      @template = Template.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def template_params
      params.require(:template).permit(:name, :description, :picture)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/templates_helper.rb
module TemplatesHelper
end

app/views/blox/_footer.html.erb
<!-- Footer -->
<footer class="gastroDev-center gastroDev-black gastroDev-padding-64 gastroDev-opacity gastroDev-hover-opacity-off">
  <a href="#home" class="gastroDev-button gastroDev-light-grey"><i class="fa fa-arrow-up gastroDev-margin-right"></i>To the top</a>
  <div class="gastroDev-xlarge gastroDev-section">
    <i class="fa fa-facebook-official gastroDev-hover-opacity"></i>
    <i class="fa fa-instagram gastroDev-hover-opacity"></i>
    <i class="fa fa-snapchat gastroDev-hover-opacity"></i>
    <i class="fa fa-pinterest-p gastroDev-hover-opacity"></i>
    <i class="fa fa-twitter gastroDev-hover-opacity"></i>
    <i class="fa fa-linkedin gastroDev-hover-opacity"></i>
  </div>
  <p>Powered by <a href="#" title="gastroDev.CSS" target="_blank" class="gastroDev-hover-text-green">gastroDev.css</a></p>
</footer>

app/views/blox/_navbar.html.erb
<!-- Navbar (sit on top) -->
<div class="gastroDev-top">
  <div class="gastroDev-bar" id="myNavbar">
    <a class="gastroDev-bar-item gastroDev-button gastroDev-hover-black gastroDev-hide-medium gastroDev-hide-large gastroDev-right" href="javascript:void(0);" onclick="toggleFunction()" title="Toggle Navigation Menu">
      <i class="fa fa-bars"></i>
    </a>
    <a href="#home" class="gastroDev-bar-item gastroDev-button">HOME</a>
    <a href="#about" class="gastroDev-bar-item gastroDev-button gastroDev-hide-small"><i class="fa fa-user"></i> ABOUT</a>
    <a href="#portfolio" class="gastroDev-bar-item gastroDev-button gastroDev-hide-small"><i class="fa fa-th"></i> PORTFOLIO</a>
    <a href="#contact" class="gastroDev-bar-item gastroDev-button gastroDev-hide-small"><i class="fa fa-envelope"></i> CONTACT</a>
    <a href="#" class="gastroDev-bar-item gastroDev-button gastroDev-hide-small gastroDev-right gastroDev-hover-red">
      <i class="fa fa-search"></i>
    </a>
  </div>

  <!-- Navbar on small screens -->
  <div id="navDemo" class="gastroDev-bar-block gastroDev-white gastroDev-hide gastroDev-hide-large gastroDev-hide-medium">
    <a href="#about" class="gastroDev-bar-item gastroDev-button" onclick="toggleFunction()">ABOUT</a>
    <a href="#portfolio" class="gastroDev-bar-item gastroDev-button" onclick="toggleFunction()">PORTFOLIO</a>
    <a href="#contact" class="gastroDev-bar-item gastroDev-button" onclick="toggleFunction()">CONTACT</a>
    <a href="#" class="gastroDev-bar-item gastroDev-button">SEARCH</a>
  </div>
</div>

app/views/blox/_parallax.html.erb
<script type="text/javascript">
  function onClick(element) {
    document.getElementById("img01").src = element.src;
    document.getElementById("modal01").style.display = "block";
    var captionText = document.getElementById("caption");
    captionText.innerHTML = element.alt;
  }

  // Change style of navbar on scroll
  window.onscroll = function() {myFunction()};
  function myFunction() {
      var navbar = document.getElementById("myNavbar");
      if (document.body.scrollTop > 100 || document.documentElement.scrollTop > 100) {
          navbar.className = "gastroDev-bar" + " gastroDev-card" + " gastroDev-animate-top" + " gastroDev-white";
      } else {
          navbar.className = navbar.className.replace(" gastroDev-card gastroDev-animate-top gastroDev-white", "");
      }
  }

  // Used to toggle the menu on small screens when clicking on the menu button
  function toggleFunction() {
      var x = document.getElementById("navDemo");
      if (x.className.indexOf("gastroDev-show") == -1) {
          x.className += " gastroDev-show";
      } else {
          x.className = x.className.replace(" gastroDev-show", "");
      }
  }  
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gastroconsult</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/devicons/devicon@master/devicon.min.css">

  </head>

  <body>


  <%= yield %>

  <!-- The core Firebase JS SDK is always required and must be listed first -->
  <script src="https://www.gstatic.com/firebasejs/8.2.0/firebase-app.js"></script>

  <!-- TODO: Add SDKs for Firebase products that you want to use
       https://firebase.google.com/docs/web/setup#available-libraries -->
  <script src="https://www.gstatic.com/firebasejs/8.2.0/firebase-analytics.js"></script>

  
  </body>


</html>

app/views/pages/home.html.erb
<style media="screen">
  body {
    background-image: url(https://gastroben.s3.amazonaws.com/bendev/codelounge.jpg);
      background-position: center;
  }



.centerGastro {
  margin: 0;
  position: absolute;
  top: 50%;
  left: 50%;
  -ms-transform: translate(-50%, -50%);
  transform: translate(-50%, -50%);
  justify-content: center;
}
</style>


<div class="containerGastro">
  <div class="centerGastro">
    <%= link_to "Enter", templates_path, :class => 'btn btn-primary'  %>
  </div>
</div>

app/views/templates/_form.html.erb
<%= form_with(model: template, local: true) do |form| %>
  <% if template.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(template.errors.count, "error") %> prohibited this template from being saved:</h2>

      <ul>
        <% template.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :picture %>
    <%= form.file_field :picture %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/templates/edit.html.erb
<h1>Editing Template</h1>

<%= render 'form', template: @template %>

<%= link_to 'Show', @template %> |
<%= link_to 'Back', templates_path %>

app/views/templates/index.html.erb
<%= render 'blox/navbar' %>
<!-- First Parallax Image with Logo Text -->
<div class="bgimg-1 gastroDev-display-container gastroDev-opacity-min" id="home">
  <div class="gastroDev-display-middle" style="white-space:nowrap;">
  </div>
</div>

<!-- Container (About Section) -->
<div class="gastroDev-content gastroDev-container gastroDev-padding-64" id="about">
  <h3 class="gastroDev-center">ABOUT ME</h3>
  <div class="gastroDev-row">
    <div class="gastroDev-col m6 gastroDev-center gastroDev-padding-large">
      <img src="https://gastroben.s3.amazonaws.com/Self/wpbfilter.jpg" class="gastroDev-round gastroDev-image gastroDev-opacity gastroDev-hover-opacity-off" alt="Photo of Me" width="500" height="333">
    </div>
    <!-- Hide this text on small devices -->
    <div class="gastroDev-col m6 gastroDev-hide-small gastroDev-padding-large">
      <p>Welcome to my consulting website! I am a full-stack developer with my coding skills based in <i class="devicon-ruby-plain colored"></i></i> and <i class="devicon-rails-plain-wordmark colored"></i>.
        </p>
    </div>

    <!-- Responsive Grid. Four columns on tablets, laptops and desktops. Will stack on mobile devices/small screens (100% width) -->
    <div class="gastroDev-row-padding gastroDev-center">
      <div class="gastroDev-col m3">
        <img src="https://gastroben.s3.amazonaws.com/Self/ams.jpg" style="width:100%" onclick="onClick(this)" class="gastroDev-hover-opacity" alt="Freezing in the Europe on my anti-valentines day vacation.">
      </div>
      <div class="gastroDev-col m3">
        <img src="https://gastroben.s3.amazonaws.com/Self/tron.jpeg" style="width:100%" onclick="onClick(this)" class="gastroDev-hover-opacity" alt="Tron Master">
      </div>
      <div class="gastroDev-col m3">
        <img src="https://gastroben.s3.amazonaws.com/Self/ams.jpg" style="width:100%" onclick="onClick(this)" class="gastroDev-hover-opacity" alt="Bear closeup">
      </div>
      <div class="gastroDev-col m3">
        <img src="https://gastroben.s3.amazonaws.com/Self/ams.jpg" style="width:100%" onclick="onClick(this)" class="gastroDev-hover-opacity" alt="Quiet ocean">
      </div>
    </div>

    <div class="gastroDev-row-padding gastroDev-center gastroDev-section">
      <div class="gastroDev-col m3">
        <img src="https://gastroben.s3.amazonaws.com/Self/thaibar.jpg" style="width:100%" onclick="onClick(this)" class="gastroDev-hover-opacity" alt="A little bit of editing to my Thai beer garden photo">
      </div>
      <div class="gastroDev-col m3">
        <img src="https://gastroben.s3.amazonaws.com/Self/thaibar.jpg" style="width:100%" onclick="onClick(this)" class="gastroDev-hover-opacity" alt="My beloved typewriter">
      </div>
      <div class="gastroDev-col m3">
        <img src="https://gastroben.s3.amazonaws.com/Self/thaibar.jpg" style="width:100%" onclick="onClick(this)" class="gastroDev-hover-opacity" alt="Empty ghost train">
      </div>
      <div class="gastroDev-col m3">
        <img src="https://gastroben.s3.amazonaws.com/Self/thaibar.jpg" style="width:100%" onclick="onClick(this)" class="gastroDev-hover-opacity" alt="Sailing">
      </div>
    </div>
  </div>
</div>

  <p class="gastroDev-large gastroDev-center gastroDev-padding-16">Im really good at:</p>
  <p class="gastroDev-wide"><i class="devicon-rails-plain-wordmark colored"></i>Web Development</p>
  <div class="gastroDev-light-grey">
    <div class="gastroDev-container gastroDev-padding-small gastroDev-dark-grey gastroDev-center" style="width:90%">90%</div>
  </div>
  <p class="gastroDev-wide"><i class="devicon-ruby-plain colored"></i>Ruby</p>
  <div class="gastroDev-light-grey">
    <div class="gastroDev-container gastroDev-padding-small gastroDev-dark-grey gastroDev-center" style="width:85%">85%</div>
  </div>
  <p class="gastroDev-wide"><i class="fa fa-photo"></i>Photo Editing</p>
  <div class="gastroDev-light-grey">
    <div class="gastroDev-container gastroDev-padding-small gastroDev-dark-grey gastroDev-center" style="width:75%">75%</div>
  </div>
</div>
</br></br></br></br>
<div class="row services text-center">
      <div data-animate="fadeInUp" class="col-lg-3">
        <div class="icon">
          <i class="devicon-html5-plain colored" style='font-size:48px;'></i>
          <i class="devicon-css3-plain-wordmark" style='font-size:48px;'></i>
          <i class="devicon-ruby-plain colored"style='font-size:48px;'></i></i>
          <i class="devicon-javascript-plain" style='font-size:48px;'></i>
        </br>
          <i class="devicon-postgresql-plain-wordmark colored" style='font-size:48px;'></i>
          <i class="devicon-linux-plain" style='font-size:48px;'></i>
          <i class="devicon-git-plain" style='font-size:48px;'></i>
          <i class="devicon-heroku-original-wordmark colored" style='font-size:48px;'></i>
        </br>
          <i class="devicon-java-plain-wordmark" style='font-size:48px;'></i>
          <i class="devicon-slack-plain colored" style='font-size:48px;'></i>
          <i class="devicon-python-plain-wordmark colored" style='font-size:48px;'></i>
          <i class="devicon-django-line-wordmark" style='font-size:48px;'></i>
        </div>
        <h3 class="heading mb-3 text-400">Full Stack Dev</h3>
        <p class="text-center description">Listed in order of experience</p>
      </div>

      <div data-animate="fadeInUp" class="col-lg-3">
        <div class="icon"><i class="fa fa-coffee"></i></div>
        <h3 class="heading mb-3 text-400">Hospitality</h3>
        <p class="text-center description">10+ Years of service industry experience.</p>
      </div>

      <div data-animate="fadeInUp" class="col-lg-3">
        <div class="icon">
          <i class="fas fa-tools" style='font-size:48px;'></i>
        </div>
        <h3 class="heading mb-3 text-400">Mech and Tech</h3>
        <p class="text-center description">Automotive repair, A/V setup, computer repair</p>
      </div>

      <div data-animate="fadeInUp" class="col-lg-3">
        <div class="icon">
          <i class="fas fa-cash-register" style='font-size:48px;'></i>
        </div>
        <h3 class="heading mb-3 text-400">Sales</h3>
        <p class="text-center description">Automotive, service industry, construction, tech, B2C.</p>
      </div>

    </div>

<div class="gastroDev-row gastroDev-center gastroDev-dark-grey gastroDev-padding-16">
  <div class="gastroDev-quarter gastroDev-section">
    <span class="gastroDev-xlarge">14+</span><br>
    Partners
  </div>
  <div class="gastroDev-quarter gastroDev-section">
    <span class="gastroDev-xlarge">55+</span><br>
    Projects Done
  </div>
  <div class="gastroDev-quarter gastroDev-section">
    <span class="gastroDev-xlarge">89+</span><br>
    Happy Clients
  </div>
  <div class="gastroDev-quarter gastroDev-section">
    <span class="gastroDev-xlarge">150+</span><br>
    Meetings
  </div>
</div>


<!-- Second Parallax Image with Portfolio Text -->
<div class="bgimg-2 gastroDev-display-container gastroDev-opacity-min">
  <div class="gastroDev-display-middle">
    <span class="gastroDev-xxlarge gastroDev-text-white gastroDev-wide">PORTFOLIO</span>
  </div>
</div>

<!-- Container (Portfolio Section) -->
<div class="gastroDev-content gastroDev-container gastroDev-padding-64" id="portfolio">
  <h3 class="gastroDev-center">MY WORK</h3>
  <p class="gastroDev-center"><em>Here are some of my latest lorem work ipsum tipsum.<br> Click on the images to make them bigger</em></p><br>
</div>
<!-- App (Portfolio Section) -->
<div class="container card-columns">
  <div class="card" style="width:300px">
    <img class="card-img-top" src="https://gastroben.s3.amazonaws.com/Self/geitnerrealtor.png" alt="Card image" style="width:100%">
    <div class="card-body">
      <h4 class="card-title">Geitner Realtor </h4>
      <p class="card-text">Rails app with ActiveAdmin to create property listings from backend.</p>
      <a href="https://whispering-sea-49760.herokuapp.com/" class="btn btn-primary">See Profile</a>
    </div>
  </div>
  <div class="card" style="width:300px">
    <img class="card-img-top" src="https://gastroben.s3.amazonaws.com/Self/resttemp1.png" alt="Card image" style="width:100%">
    <div class="card-body">
      <h4 class="card-title">Restaurant Template 1</h4>
      <p class="card-text">Rails app with custom back end to add menu items to front end with filter for display.  </p>
      <a href="https://resttemp.herokuapp.com/" class="btn btn-primary">See Profile</a>
    </div>
  </div>
  <div class="card" style="width:300px">
    <img class="card-img-top" src="https://gastroben.s3.amazonaws.com/Self/reactrec.png" alt="Card image" style="width:100%">
    <div class="card-body">
      <h4 class="card-title">React app</h4>
      <p class="card-text">Simple recipie app built with react</p>
      <a href="https://reactbloggastro.herokuapp.com/" class="btn btn-primary">See Profile</a>
    </div>
  </div>
  <div class="card" style="width:300px">
    <img class="card-img-top" src="https://gastroben.s3.amazonaws.com/Self/basic .png" alt="Card image" style="width:100%">
    <div class="card-body">
      <h4 class="card-title">CRUD template</h4>
      <p class="card-text">Plain rails app with ActiveAdmin CRUD backend</p>
      <a href="https://mysterious-castle-65360.herokuapp.com/" class="btn btn-primary">See Profile</a>
    </div>
  </div>
  <div class="card" style="width:300px">
    <img class="card-img-top" src="https://gastroben.s3.amazonaws.com/Self/resttemp2.jpeg" alt="Card image" style="width:100%">
    <div class="card-body">
      <h4 class="card-title">Restaurant Template 2</h4>
      <p class="card-text">Restaurant template 2 with JS menu display</p>
      <a href="https://lit-tor-84285.herokuapp.com/" class="btn btn-primary">See Profile</a>
    </div>
  </div>
  <div class="card" style="width:300px">
    <img class="card-img-top" src="https://gastroben.s3.amazonaws.com/Self/dashbrd.jpeg" alt="Card image" style="width:100%">
    <div class="card-body">
      <h4 class="card-title">Blog Template</h4>
      <p class="card-text">Rails app with users, blog and public messages displayed in custom backend dashboard</p>
      <a href="https://gastronomicdev.herokuapp.com/" class="btn btn-primary">See Profile</a>
    </div>
  </div>
</div>


<!-- Modal for full size images on click-->
<div id="modal01" class="gastroDev-modal gastroDev-black" onclick="this.style.display='none'">
  <span class="gastroDev-button gastroDev-large gastroDev-black gastroDev-display-topright" title="Close Modal Image"><i class="fa fa-remove"></i></span>
  <div class="gastroDev-modal-content gastroDev-animate-zoom gastroDev-center gastroDev-transparent gastroDev-padding-64">
    <img id="img01" class="gastroDev-image">
    <p id="caption" class="gastroDev-opacity gastroDev-large"></p>
  </div>
</div>

<!-- Third Parallax Image with Portfolio Text -->
<div class="bgimg-3 gastroDev-display-container gastroDev-opacity-min">
  <div class="gastroDev-display-middle">
     <span class="gastroDev-xxlarge gastroDev-text-white gastroDev-wide">CONTACT</span>
  </div>
</div>

<!-- Container (Contact Section) -->
<div class="gastroDev-content gastroDev-container gastroDev-padding-64" id="contact">
  <h3 class="gastroDev-center">WHERE I WORK</h3>
  <p class="gastroDev-center"><em>I'd love your feedback!</em></p>

  <div class="gastroDev-row gastroDev-padding-32 gastroDev-section">
    <div class="gastroDev-col m4 gastroDev-container">
      <img src="https://gastroben.s3.amazonaws.com/Self/jupiterbeach.jpg" class="gastroDev-image gastroDev-round" style="width:100%">
    </div>
    <div class="gastroDev-col m8 gastroDev-panel">
      <div class="gastroDev-large gastroDev-margin-bottom">
        <i class="fa fa-map-marker fa-fw gastroDev-hover-text-black gastroDev-xlarge gastroDev-margin-right"></i> Florida, US<br>
        <i class="fa fa-phone fa-fw gastroDev-hover-text-black gastroDev-xlarge gastroDev-margin-right"></i> Phone: 786-860-2661<br>
        <i class="fa fa-envelope fa-fw gastroDev-hover-text-black gastroDev-xlarge gastroDev-margin-right"></i> Email: nextbendev@gmail.com<br>
      </div>
      <p>Swing by for a cup of <i class="fa fa-coffee"></i>, or leave me a note:</p>
      <form action="/action_page.php" target="_blank">
        <div class="gastroDev-row-padding" style="margin:0 -16px 8px -16px">
          <div class="gastroDev-half">
            <input class="gastroDev-input gastroDev-border" type="text" placeholder="Name" required name="Name">
          </div>
          <div class="gastroDev-half">
            <input class="gastroDev-input gastroDev-border" type="text" placeholder="Email" required name="Email">
          </div>
        </div>
        <input class="gastroDev-input gastroDev-border" type="text" placeholder="Message" required name="Message">
        <button class="gastroDev-button gastroDev-black gastroDev-right gastroDev-section" type="submit">
          <i class="fa fa-paper-plane"></i> SEND MESSAGE
        </button>
      </form>
    </div>
  </div>
</div>




<%= render 'blox/footer' %>
<%= render 'blox/parallax' %>

app/views/templates/new.html.erb
<h1>New Template</h1>

<%= render 'form', template: @template %>

<%= link_to 'Back', templates_path %>

app/views/templates/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @template.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @template.description %>
</p>

<p>
  <strong>Picture:</strong>
  <%= image_tag(@template.picture_url, width: 600) if @template.picture.present? %>
</p>

<%= link_to 'Edit', edit_template_path(@template) %> |
<%= link_to 'Back', templates_path %>